# Generated by Django 5.1.7 on 2025-04-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
